In [1]:
import nltk
nltk.download('gutenberg')
from nltk.corpus import gutenberg
import pandas as pd


[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\sunil\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\gutenberg.zip.


In [2]:
data = gutenberg.raw('shakespeare-hamlet.txt')

In [3]:
with open('hamlet.txt','w') as file:
    file.write(data)

In [4]:
with open('hamlet.txt','r') as file:
    text = file.read().lower()

In [5]:
text

"[the tragedie of hamlet by william shakespeare 1599]\n\n\nactus primus. scoena prima.\n\nenter barnardo and francisco two centinels.\n\n  barnardo. who's there?\n  fran. nay answer me: stand & vnfold\nyour selfe\n\n   bar. long liue the king\n\n   fran. barnardo?\n  bar. he\n\n   fran. you come most carefully vpon your houre\n\n   bar. 'tis now strook twelue, get thee to bed francisco\n\n   fran. for this releefe much thankes: 'tis bitter cold,\nand i am sicke at heart\n\n   barn. haue you had quiet guard?\n  fran. not a mouse stirring\n\n   barn. well, goodnight. if you do meet horatio and\nmarcellus, the riuals of my watch, bid them make hast.\nenter horatio and marcellus.\n\n  fran. i thinke i heare them. stand: who's there?\n  hor. friends to this ground\n\n   mar. and leige-men to the dane\n\n   fran. giue you good night\n\n   mar. o farwel honest soldier, who hath relieu'd you?\n  fra. barnardo ha's my place: giue you goodnight.\n\nexit fran.\n\n  mar. holla barnardo\n\n   bar. 

In [6]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from sklearn.model_selection import train_test_split

In [7]:
tokenizer = Tokenizer()

In [8]:
tokenizer.fit_on_texts([text])

In [9]:
total_words =len(tokenizer.word_index)+1
total_words

4818

In [10]:
tokenizer.word_index

{'the': 1,
 'and': 2,
 'to': 3,
 'of': 4,
 'i': 5,
 'you': 6,
 'a': 7,
 'my': 8,
 'it': 9,
 'in': 10,
 'that': 11,
 'ham': 12,
 'is': 13,
 'not': 14,
 'his': 15,
 'this': 16,
 'with': 17,
 'your': 18,
 'but': 19,
 'for': 20,
 'me': 21,
 'lord': 22,
 'as': 23,
 'what': 24,
 'he': 25,
 'be': 26,
 'so': 27,
 'him': 28,
 'haue': 29,
 'king': 30,
 'will': 31,
 'no': 32,
 'our': 33,
 'we': 34,
 'on': 35,
 'are': 36,
 'if': 37,
 'all': 38,
 'then': 39,
 'shall': 40,
 'by': 41,
 'thou': 42,
 'come': 43,
 'or': 44,
 'hamlet': 45,
 'good': 46,
 'do': 47,
 'hor': 48,
 'her': 49,
 'let': 50,
 'now': 51,
 'thy': 52,
 'how': 53,
 'more': 54,
 'they': 55,
 'from': 56,
 'enter': 57,
 'at': 58,
 'was': 59,
 'oh': 60,
 'like': 61,
 'most': 62,
 'there': 63,
 'well': 64,
 'know': 65,
 'selfe': 66,
 'would': 67,
 'them': 68,
 'loue': 69,
 'may': 70,
 "'tis": 71,
 'vs': 72,
 'sir': 73,
 'qu': 74,
 'which': 75,
 'did': 76,
 'why': 77,
 'laer': 78,
 'giue': 79,
 'thee': 80,
 'ile': 81,
 'must': 82,
 'hath': 

In [11]:
input_sequences = []
for line in text.split('\n'):
    token_list = tokenizer.texts_to_sequences([line])[0]
    for i in range(1,len(token_list)):
        n_gram_sequence = token_list[:i+1]
        input_sequences.append(n_gram_sequence)

print(input_sequences)

[[1, 687], [1, 687, 4], [1, 687, 4, 45], [1, 687, 4, 45, 41], [1, 687, 4, 45, 41, 1886], [1, 687, 4, 45, 41, 1886, 1887], [1, 687, 4, 45, 41, 1886, 1887, 1888], [1180, 1889], [1180, 1889, 1890], [1180, 1889, 1890, 1891], [57, 407], [57, 407, 2], [57, 407, 2, 1181], [57, 407, 2, 1181, 177], [57, 407, 2, 1181, 177, 1892], [407, 1182], [407, 1182, 63], [408, 162], [408, 162, 377], [408, 162, 377, 21], [408, 162, 377, 21, 247], [408, 162, 377, 21, 247, 882], [18, 66], [451, 224], [451, 224, 248], [451, 224, 248, 1], [451, 224, 248, 1, 30], [408, 407], [451, 25], [408, 6], [408, 6, 43], [408, 6, 43, 62], [408, 6, 43, 62, 1893], [408, 6, 43, 62, 1893, 96], [408, 6, 43, 62, 1893, 96, 18], [408, 6, 43, 62, 1893, 96, 18, 566], [451, 71], [451, 71, 51], [451, 71, 51, 1894], [451, 71, 51, 1894, 567], [451, 71, 51, 1894, 567, 378], [451, 71, 51, 1894, 567, 378, 80], [451, 71, 51, 1894, 567, 378, 80, 3], [451, 71, 51, 1894, 567, 378, 80, 3, 273], [451, 71, 51, 1894, 567, 378, 80, 3, 273, 1181], [40

In [12]:
max_sequences_len = max([len(x) for x in input_sequences])
max_sequences_len

14

In [13]:
input_sequences = np.array(pad_sequences(input_sequences,maxlen=max_sequences_len,padding='pre'))
input_sequences

array([[   0,    0,    0, ...,    0,    1,  687],
       [   0,    0,    0, ...,    1,  687,    4],
       [   0,    0,    0, ...,  687,    4,   45],
       ...,
       [   0,    0,    0, ...,    4,   45, 1047],
       [   0,    0,    0, ...,   45, 1047,    4],
       [   0,    0,    0, ..., 1047,    4,  193]])

In [14]:
import tensorflow as tf


In [15]:
x,y = input_sequences[:,:-1],input_sequences[:,-1]

In [16]:
x,y

(array([[   0,    0,    0, ...,    0,    0,    1],
        [   0,    0,    0, ...,    0,    1,  687],
        [   0,    0,    0, ...,    1,  687,    4],
        ...,
        [   0,    0,    0, ...,  687,    4,   45],
        [   0,    0,    0, ...,    4,   45, 1047],
        [   0,    0,    0, ...,   45, 1047,    4]]),
 array([ 687,    4,   45, ..., 1047,    4,  193]))

In [17]:
y = tf.keras.utils.to_categorical(y,num_classes=total_words)

In [18]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2)

In [19]:
from tensorflow.keras.callbacks import EarlyStopping
early_stopping = EarlyStopping(monitor='val_loss',patience=3,restore_best_weights=True)

In [20]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding,LSTM,Dense,Dropout,GRU

In [21]:
model = Sequential()
model.add(Embedding(total_words,100,input_length=max_sequences_len-1))
model.add(LSTM(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(LSTM(100))
model.add(Dense(total_words,activation="softmax"))

In [22]:
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 13, 100)           481800    
                                                                 
 lstm (LSTM)                 (None, 13, 150)           150600    
                                                                 
 dropout (Dropout)           (None, 13, 150)           0         
                                                                 
 lstm_1 (LSTM)               (None, 100)               100400    
                                                                 
 dense (Dense)               (None, 4818)              486618    
                                                                 
Total params: 1219418 (4.65 MB)
Trainable params: 1219418 (4.65 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [23]:
history = model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])

Epoch 1/50


644/644 [==============================] - 66s 81ms/step - loss: 6.9093 - accuracy: 0.0312 - val_loss: 6.7703 - val_accuracy: 0.0356
Epoch 2/50
644/644 [==============================] - 49s 76ms/step - loss: 6.4728 - accuracy: 0.0384 - val_loss: 6.8331 - val_accuracy: 0.0406
Epoch 3/50
644/644 [==============================] - 49s 76ms/step - loss: 6.3345 - accuracy: 0.0457 - val_loss: 6.8866 - val_accuracy: 0.0476
Epoch 4/50
644/644 [==============================] - 49s 77ms/step - loss: 6.1912 - accuracy: 0.0507 - val_loss: 6.9178 - val_accuracy: 0.0492


In [53]:
## GRU RNN
## Define the model
model=Sequential()
model.add(Embedding(total_words,100,input_length=max_sequence_len-1))
model.add(GRU(150,return_sequences=True))
model.add(Dropout(0.2))
model.add(GRU(100))
model.add(Dense(total_words,activation="softmax"))

# #Compile the model
model.compile(loss="categorical_crossentropy",optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 13, 100)           481800    
                                                                 
 gru (GRU)                   (None, 13, 150)           113400    
                                                                 
 dropout_1 (Dropout)         (None, 13, 150)           0         
                                                                 
 gru_1 (GRU)                 (None, 100)               75600     
                                                                 
 dense_1 (Dense)             (None, 4818)              486618    
                                                                 
Total params: 1157418 (4.42 MB)
Trainable params: 1157418 (4.42 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [54]:
history = model.fit(x_train,y_train,epochs=50,validation_data=(x_test,y_test),verbose=1,callbacks=[early_stopping])

Epoch 1/50
644/644 [==============================] - 67s 85ms/step - loss: 7.0270 - accuracy: 0.0323 - val_loss: 6.8802 - val_accuracy: 0.0216
Epoch 2/50
644/644 [==============================] - 43s 67ms/step - loss: 6.5358 - accuracy: 0.0348 - val_loss: 6.8785 - val_accuracy: 0.0439
Epoch 3/50
644/644 [==============================] - 40s 62ms/step - loss: 6.3417 - accuracy: 0.0471 - val_loss: 6.9173 - val_accuracy: 0.0424
Epoch 4/50
644/644 [==============================] - 41s 64ms/step - loss: 6.1749 - accuracy: 0.0522 - val_loss: 6.8755 - val_accuracy: 0.0581
Epoch 5/50
644/644 [==============================] - 51s 79ms/step - loss: 5.9407 - accuracy: 0.0706 - val_loss: 6.8381 - val_accuracy: 0.0692
Epoch 6/50
644/644 [==============================] - 51s 80ms/step - loss: 5.6707 - accuracy: 0.0859 - val_loss: 6.9333 - val_accuracy: 0.0744
Epoch 7/50
644/644 [==============================] - 46s 72ms/step - loss: 5.4152 - accuracy: 0.0947 - val_loss: 7.0361 - val_accuracy:

In [55]:
def predict_next_word(model,tokenizer,text,max_sequences_len):
    token_list = tokenizer.texts_to_sequences([text])[0]
    print(token_list)
    if len(token_list) >= max_sequences_len:
        token_list = token_list[-(max_sequences_len-1):]
        print(token_list)
    token_list = pad_sequences([token_list],maxlen=max_sequences_len-1,padding='pre')
    print(token_list)
    predicted = model.predict(token_list,verbose=0)
    print(predicted)
    predicted_word_index = np.argmax(predicted,axis = 1)
    print(predicted_word_index)
    for word, index in tokenizer.word_index.items():
        if index == predicted_word_index:
            return word
    return None

In [56]:
input_text = "  Barn. Last night of all,When yond same"
print(f"Input text:{input_text}")
max_sequence_len = model.input_shape[1]+1
print(max_sequences_len)
next_word = predict_next_word(model,tokenizer,input_text,max_sequences_len)
print(f"Next Word Prediction:{next_word}")

Input text:  Barn. Last night of all,When yond same
14
[346, 274, 124, 4, 38, 95, 1910, 275]
[[   0    0    0    0    0  346  274  124    4   38   95 1910  275]]
[[1.6609847e-06 1.1751141e-04 8.5448334e-04 ... 1.3510831e-06
  5.1503612e-05 1.4252805e-06]]
[22]
Next Word Prediction:lord


In [57]:
model.save("next_word_lstm.h5")

import pickle
with open('tokenizer.pickle','wb') as handle:
    pickle.dump(tokenizer,handle,protocol=pickle.HIGHEST_PROTOCOL)